<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-del-projecto-cad_equipo113/blob/main/plantilla.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Ciencia y analítica de datos**

------------------------------
Jessica Paola Pulido Vasquez
**A01793650**

Joan Sebastian Jimenez Chacón
**A01793970**

------------------------------
Proyecto final - Avance 1

1. El nombre que caracteriza el conjunto de datos: 

   **Airplane Crashes and Fatalities**. Conjunto de datos que analiza los accidentes aereos. 

2. La organización que lo generó: 
   Usuario The Devastor de Kaggle

3. Incluya un enlace de Internet donde se puedan descargar el base de datos en línea: 
    https://www.kaggle.com/datasets/thedevastator/airplane-crashes-and-fatalities/metadata

4. Describe el conjunto de datos. ¿Qué datos contiene?
- Fecha de Accidente
- Hora de Accidente
- Ubicación del Accidente
- Operador de Aeronave
- ID del vuelo
- Tipo de Arenave
- Registro
- cn/In
- Numero de persona a bordo
- Numero de fallecimientos
- Altura
- Observaciones

In [2]:
import pandas as pd
url="https://raw.githubusercontent.com/PosgradoMNA/actividades-del-projecto-cad_equipo113/main/Airplane_Crashes_and_Fatalities_Since_1908.csv"
datos=pd.read_csv(url)
datos.head()

,index,Date,Time,Location,Operator,Flight #,Route,Type,Registration,cn/In,Aboard,Fatalities,Ground,Summary
0,0,09/17/1908,17:18,"Fort Myer, Virginia",Military - U.S. Army,NaN,Demonstration,Wright Flyer III,NaN,1,2.0,1.0,0.0,"During a demonstration flight, a U.S. Army fly..."
1,1,07/12/1912,06:30,"AtlantiCity, New Jersey",Military - U.S. Navy,NaN,Test flight,Dirigible,NaN,NaN,5.0,5.0,0.0,First U.S. dirigible Akron exploded just offsh...
2,2,08/06/1913,NaN,"Victoria, British Columbia, Canada",Private,-,NaN,Curtiss seaplane,NaN,NaN,1.0,1.0,0.0,The first fatal airplane accident in Canada oc...
3,3,09/09/1913,18:30,Over the North Sea,Military - German Navy,NaN,NaN,Zeppelin L-1 (airship),NaN,NaN,20.0,14.0,0.0,The airship flew into a thunderstorm and encou...
4,4,10/17/1913,10:30,"Near Johannisthal, Germany",Military - German Navy,NaN,NaN,Zeppelin L-2 (airship),NaN,NaN,30.0,30.0,0.0,Hydrogen gas which was being vented was sucked...



5. ¿Cuáles son algunas de las preguntas de investigación que podría responder con estos datos? Enumere al menos OCHO (no responda las preguntas).

*   ¿En que ubicación hay más probabilidad de que ocurra un accidente aereo?
*   ¿Vuelos privados más peligrosos?
*   ¿Porbabilidad de no fallecer en un accidente aereo?
*   ¿Tipo de aviones con más accidentes aereos?
*   ¿Horas con mayor posibilidad de accidentes?
*   ¿Avances tecnologicos respecto a los accidentes aereos?
*   ¿Rutas que deben cambiarsen para no tener accidentes?
*   ¿Posibiliad de sobrevivir a un accidente de acuerdo a la altura del accidente?

6. ¿Qué actor (empresa, sector de la sociedad, organismo descentralizado, gobierno, etc.) estaría interesado en las preguntas mencionadas que identificó?

* Gobiernos (normatividad aerea)
* Aerolineas
* Industria de la aviación
* Usuarios de aerolineas